name: 自動刪除 Feature 分支，feature 分支已經全 merge 到 develop 與 Qat 分支時

on:
  push:
    branches:
      - develop
      - Qat

jobs:
  delete-feature-branch:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: 檢查並刪除已合併的 Feature 分支
      run: |
        # 取得所有遠端分支
        git fetch --all
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # 列出所有 feature 開頭的分支
        FEATURE_BRANCHES=$(git branch -r | grep 'origin/feature' | sed 's/origin\///')
        
        # 對每個 feature 分支進行檢查
        echo "開始檢查 feature 分支..."
        for branch in $FEATURE_BRANCHES; do
          echo "檢查分支: $branch"
          
          # 檢查是否同時合併到 develop 和 Qat
          MERGED_TO_DEVELOP=$(git branch -r --contains $branch | grep 'origin/develop' || true)
          MERGED_TO_QAT=$(git branch -r --contains $branch | grep 'origin/Qat' || true)
          
          if [ ! -z "$MERGED_TO_DEVELOP" ] && [ ! -z "$MERGED_TO_QAT" ]; then
            echo "分支 $branch 已合併到 develop 和 Qat，準備刪除..."
            git push origin --delete ${branch#origin/}
            echo "已刪除分支: $branch"
          else
            echo "分支 $branch 尚未完全合併到 develop 和 Qat，保留分支"
          fi
        done
