# This is a basic workflow to help you get started with Actions

name: Delete Feature Branch After Merge to DEV and QAT

on:
  push:
    branches: [ "featureA" ]
  pull_request:
    types: [closed]  # 當 PR 被關閉（即合併）時觸發
    branches:
      - develop
      - Qat

jobs:
  delete-feature-branch:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

