# This is a basic workflow to help you get started with Actions

name: LouisTest

on:
  push:
    branches: [ "featureA" ]
  pull_request:
    types: [closed]  # 當 PR 被關閉（即合併）時觸發
    branches:
      - develop
      - Qat

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Run echo
      run: echo Hello, World!
      
   # - name: Set up Git
   #   run: |
   #     git config user.name "GitHub Actions"
   #     git config user.email "actions@github.com"

